import React from 'react';
export const astDetails = () => <div>ast distinct</div>;
export const ast_detail_0 = (p:any)=> <div>ast 0 nodes</div>;
export const ast_detail_1 = (p:any)=> <div>ast 1 types</div>;
export const ast_detail_2 = (p:any)=> <div>ast 2 control flow</div>;
export const ast_detail_3 = (p:any)=> <div>ast 3 data flow</div>;
export const ast_detail_4 = (p:any)=> <div>ast 4 nodes</div>;
export const ast_detail_5 = (p:any)=> <div>ast 5 types</div>;
export const ast_detail_6 = (p:any)=> <div>ast 6 control flow</div>;
export const ast_detail_7 = (p:any)=> <div>ast 7 data flow</div>;
export const ast_detail_8 = (p:any)=> <div>ast 8 nodes</div>;
export const ast_detail_9 = (p:any)=> <div>ast 9 types</div>;
export const ast_detail_10 = (p:any)=> <div>ast 10 control flow</div>;
export const ast_detail_11 = (p:any)=> <div>ast 11 data flow</div>;
export const ast_detail_12 = (p:any)=> <div>ast 12 nodes</div>;
export const ast_detail_13 = (p:any)=> <div>ast 13 types</div>;
export const ast_detail_14 = (p:any)=> <div>ast 14 control flow</div>;
export const ast_detail_15 = (p:any)=> <div>ast 15 data flow</div>;
export const ast_detail_16 = (p:any)=> <div>ast 16 nodes</div>;
export const ast_detail_17 = (p:any)=> <div>ast 17 types</div>;
export const ast_detail_18 = (p:any)=> <div>ast 18 control flow</div>;
export const ast_detail_19 = (p:any)=> <div>ast 19 data flow</div>;