import React from 'react';
export const php_parserDetails = () => <div>php_parser distinct</div>;
export const php_parser_detail_0 = (p:any)=> <div>php_parser 0 php 5</div>;
export const php_parser_detail_1 = (p:any)=> <div>php_parser 1 php 7</div>;
export const php_parser_detail_2 = (p:any)=> <div>php_parser 2 AST</div>;
export const php_parser_detail_3 = (p:any)=> <div>php_parser 3 symbol table</div>;
export const php_parser_detail_4 = (p:any)=> <div>php_parser 4 php 5</div>;
export const php_parser_detail_5 = (p:any)=> <div>php_parser 5 php 7</div>;
export const php_parser_detail_6 = (p:any)=> <div>php_parser 6 AST</div>;
export const php_parser_detail_7 = (p:any)=> <div>php_parser 7 symbol table</div>;
export const php_parser_detail_8 = (p:any)=> <div>php_parser 8 php 5</div>;
export const php_parser_detail_9 = (p:any)=> <div>php_parser 9 php 7</div>;
export const php_parser_detail_10 = (p:any)=> <div>php_parser 10 AST</div>;
export const php_parser_detail_11 = (p:any)=> <div>php_parser 11 symbol table</div>;
export const php_parser_detail_12 = (p:any)=> <div>php_parser 12 php 5</div>;
export const php_parser_detail_13 = (p:any)=> <div>php_parser 13 php 7</div>;
export const php_parser_detail_14 = (p:any)=> <div>php_parser 14 AST</div>;
export const php_parser_detail_15 = (p:any)=> <div>php_parser 15 symbol table</div>;
export const php_parser_detail_16 = (p:any)=> <div>php_parser 16 php 5</div>;
export const php_parser_detail_17 = (p:any)=> <div>php_parser 17 php 7</div>;
export const php_parser_detail_18 = (p:any)=> <div>php_parser 18 AST</div>;
export const php_parser_detail_19 = (p:any)=> <div>php_parser 19 symbol table</div>;