import React from 'react';
export const metricsDetails = () => <div>metrics distinct</div>;
export const metrics_detail_0 = (p:any)=> <div>metrics 0 coverage</div>;
export const metrics_detail_1 = (p:any)=> <div>metrics 1 equivalence score</div>;
export const metrics_detail_2 = (p:any)=> <div>metrics 2 LOC delta</div>;
export const metrics_detail_3 = (p:any)=> <div>metrics 3 coverage</div>;
export const metrics_detail_4 = (p:any)=> <div>metrics 4 equivalence score</div>;
export const metrics_detail_5 = (p:any)=> <div>metrics 5 LOC delta</div>;
export const metrics_detail_6 = (p:any)=> <div>metrics 6 coverage</div>;
export const metrics_detail_7 = (p:any)=> <div>metrics 7 equivalence score</div>;
export const metrics_detail_8 = (p:any)=> <div>metrics 8 LOC delta</div>;
export const metrics_detail_9 = (p:any)=> <div>metrics 9 coverage</div>;
export const metrics_detail_10 = (p:any)=> <div>metrics 10 equivalence score</div>;
export const metrics_detail_11 = (p:any)=> <div>metrics 11 LOC delta</div>;
export const metrics_detail_12 = (p:any)=> <div>metrics 12 coverage</div>;
export const metrics_detail_13 = (p:any)=> <div>metrics 13 equivalence score</div>;
export const metrics_detail_14 = (p:any)=> <div>metrics 14 LOC delta</div>;
export const metrics_detail_15 = (p:any)=> <div>metrics 15 coverage</div>;
export const metrics_detail_16 = (p:any)=> <div>metrics 16 equivalence score</div>;
export const metrics_detail_17 = (p:any)=> <div>metrics 17 LOC delta</div>;
export const metrics_detail_18 = (p:any)=> <div>metrics 18 coverage</div>;
export const metrics_detail_19 = (p:any)=> <div>metrics 19 equivalence score</div>;