import React from 'react';
export const cobol_parserDetails = () => <div>cobol_parser distinct</div>;
export const cobol_parser_detail_0 = (p:any)=> <div>cobol_parser 0 DIVISION</div>;
export const cobol_parser_detail_1 = (p:any)=> <div>cobol_parser 1 PIC 9(5)</div>;
export const cobol_parser_detail_2 = (p:any)=> <div>cobol_parser 2 PERFORM</div>;
export const cobol_parser_detail_3 = (p:any)=> <div>cobol_parser 3 COPY</div>;
export const cobol_parser_detail_4 = (p:any)=> <div>cobol_parser 4 DIVISION</div>;
export const cobol_parser_detail_5 = (p:any)=> <div>cobol_parser 5 PIC 9(5)</div>;
export const cobol_parser_detail_6 = (p:any)=> <div>cobol_parser 6 PERFORM</div>;
export const cobol_parser_detail_7 = (p:any)=> <div>cobol_parser 7 COPY</div>;
export const cobol_parser_detail_8 = (p:any)=> <div>cobol_parser 8 DIVISION</div>;
export const cobol_parser_detail_9 = (p:any)=> <div>cobol_parser 9 PIC 9(5)</div>;
export const cobol_parser_detail_10 = (p:any)=> <div>cobol_parser 10 PERFORM</div>;
export const cobol_parser_detail_11 = (p:any)=> <div>cobol_parser 11 COPY</div>;
export const cobol_parser_detail_12 = (p:any)=> <div>cobol_parser 12 DIVISION</div>;
export const cobol_parser_detail_13 = (p:any)=> <div>cobol_parser 13 PIC 9(5)</div>;
export const cobol_parser_detail_14 = (p:any)=> <div>cobol_parser 14 PERFORM</div>;
export const cobol_parser_detail_15 = (p:any)=> <div>cobol_parser 15 COPY</div>;
export const cobol_parser_detail_16 = (p:any)=> <div>cobol_parser 16 DIVISION</div>;
export const cobol_parser_detail_17 = (p:any)=> <div>cobol_parser 17 PIC 9(5)</div>;
export const cobol_parser_detail_18 = (p:any)=> <div>cobol_parser 18 PERFORM</div>;
export const cobol_parser_detail_19 = (p:any)=> <div>cobol_parser 19 COPY</div>;